diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
http.proxy=http://172.25.1.2:3129
http.postbuffer=524288000
http.version=HTTP/2
https.proxy=https://172.25.1.2:3129
https.postbuffer=52428800
user.email=donaldmabbery92812@gmail.com
user.name=youngelit0812
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/youngelit0812/Frontend_for_sol.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.frontend.remote=origin
branch.frontend.merge=refs/heads/frontend
